### ISSUE TITLE
[Feature] Add the ability to be funny

### ISSUE THREAD

**Issue by michaeltout** [MvonK/archibald#12]
**Is your feature request related to a problem? Please describe.**
The bot currently lacks the ability to be funny, see (https://en.wikipedia.org/wiki/Humour for details on this topic)

**Describe the solution you'd like**
[This PR](https://github.com/RedKinda/archibald/pull/11) implements this feature.

**Describe alternatives you've considered**
Other alternatives involve a refactoring of code that would be largely more work than the advised solution.

**Additional context**
![Screenshot 2023-11-22 at 20 17 24](https://github.com/RedKinda/archibald/assets/15999936/258b8177-3944-4de0-a25b-32e18d3e2dce)
This above picture illustrates things that indicate the lack of this feature

**Comment by dr-noid** [comment]
This is a very insightful issue and I think the core maintainers should take a good look at this.

**Comment by RedKinda** [comment]
Great idea! However, I will be locking this issue due to the mention of the year 1489.
